[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxfixes",
  "libxrandr",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]
